apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "trraks"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "trraks"
    spec:
      containers:
        - name: "trraks"
          image: "trracr.azurecr.io/trraks"
          ports:
          - containerPort: 80